### ISSUE TITLE
[BUG] Subscription via Payments results in Bad Request error.

### ISSUE THREAD

**Issue by Jovian-Dsouza** [nevermined-io/tutorials_legacy#40]
## Describe the bug
Unable to create subscription using payments sdk, Running the example code (https://github.com/nevermined-io/tutorials/tree/main/payments-nextjs-example) and clicking on Create subscription button gives Bad request error
```
async function createSubscription() {
  if (payments.isLoggedIn) {
    const { did } = await payments.createSubscription({
      name: "test subscription",
      description: "test",
      price: 10000000n,
      tokenAddress: "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d",
      duration: 30,
      tags: ["test"],
    });
  }
}
```

##  To Reproduce
- Following the tutorial https://github.com/nevermined-io/tutorials/tree/main/payments-nextjs-example

## Expected behavior
- Should create the subscription

## Screenshots
![image](https://github.com/nevermined-io/tutorials/assets/43859106/80c6feb0-1eab-4ee3-9386-51ae17a1c4dc)

**Comment by eruizgar91** [comment]
Hi @Jovian-Dsouza, we were yesterday updating this turorial, please feel free to check again with the new release of our library. Thank you :)

**Comment by Jovian-Dsouza** [comment]
> Hi @Jovian-Dsouza, we were yesterday updating this turorial, please feel free to check again with the new release of our library. Thank you :)

Thanks @eruizgar91 , will check it
